plugin: aws_ec2
regions:
  - eu-west-1
filters:
  instance-state-name: running
  tag:Environment: prod
strict: False

boto_profile: pciapp

hostnames:
  - aliases
  - tag:Name
  - ip-address
  - private-ip-address

compose:
  ansible_host: private_ip_address